appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: w8ByIrqgHYkUaCrYw0PcYN+H4GKuZCgjb6ylRo7oETdvQ/zq1iu76IK1FEZxbK6PhJ1nJFaZeaJNm//GGe+VOhkNpy6IzJR0SzqaopYbcAejEwF2EvBkEC/s1DTubFHr00RSaoFOUpBmOTqhcfI32J0iGHRc/kKCx0IPEeQzoMCsBtYlJFNAxmZ1Iu5TsKW+FbKFnJ0uA2nwOweE63GHhNfzTfxobYToEfqC18CHTMRQsJn80mD9MUndimWJZyq19EuLSmxNeuFG6/X5l1UbFT9YZX8BvE2dZbgGnW4K40+2UlfNLygGvxXnr3cYlZcr0k+qVN1FYtsQdgScRNgbEM4o6Hz6McsPkePU7vFh4W7jWuiCzjuYNf/9ELtCgDxdxKbjgxULlQC4GbbWpfEszJEgfyC/MiUGsXOy5o2xgSfYotFbCV7SYrmknvDPwaIMvfJeXoledskNlICMGZrk3ReJRdr0i0bJzwp6fRv0j4WxeZFeyRTE1/O60JE/sGPLTauHhufegVAtg3kzSscduoPUlstQPibGSJOSwma1l4uJZOEctd6sdWb1XQfIH8HqaKn382MixGapqlupR2WN4gAUdaKYqAguWHmOnNbI4XyroLY5IX3ZxxY5Rs+h8pdqN31mqRQq0ra/bUFN+vG/qH00KTPqrKYUDdiGVqB475Y=}
