travis:
  secure:
    BINSTAR_TOKEN: PdHIA+Bvj5jnnlr+eZ2Uvh1mdcEX2nAa0bgKb50KvMOJG4rByzPH3latJJW/tpHwpvBLAh/ZW1voL4oq73dB39JKnrs29wT08zdFNb74n2jV6A8nXaxkP6Jg2on1vdhOLnF3aTr2wBs0nBmELF5XJEhGhHW2u9G+tsy+OxLfVbzQ42t6SyNWkMWXPO5Y+NYX/y3YNk6ebZL17IbEAHoTlF2arYcAuOK0NzMH+GsVU5lLDMnhMgYT1IOvPSa6CkSorb9MU4JtO8/M8iXtICbWejnN66gW7bKCvbt6EbIURk3AWHP/3ASmIeFDXxrLH/O5fXPoCiLUbvTjjmO889OyQsD4ba92t4dL5yJiv7kI0+I4QX0wleRhKXVi2KPf9SbEPGxBOaJagzk8kDmTIj3/XBS8SCAhxsvh/BPjaABcMxwQJ3X7M7GK4ETU7tp9NiHWxVaRbkzK1n2VpIp0G8CLQuQeKIJ49ozidikxhFMN655cqBJewaz+8QY+ycXztBGzUYZN/8VqKvRd8FVbK/TKND7GUpQi10PQ23vwDqiwo3XR8FYQ1hlaa68W1nchItSOoiRPjO1WnwJwovmD25WdvBmgHw84dPyjdVfdKAcwjqJBOREhKo6tmkkeXeQpR1I5hNp9W8pck03/3EEWkSWyQBO0C6L6IICiy5enyE1qDzU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
