travis:
  secure:
    BINSTAR_TOKEN: qXW7rUTVtLbNysYNJ9TYYsnKDZeDmdXhhaArvwsY4q+SXLv5tJO1p4tl7th2g+UXsEZHlmWEyNOrFN1PuWxO+zMknp07Tn1yY7V9N/89XBKKdZf/f+uvxuMkFNOfZJr+xxCOAYKJiZ1Y+CXQiOu8xrEonl9aZ+4FGQTJRuopV/t8WfArXXUB5s62Ls7IvqwPUfvkdh7xs2vgDthtHDKufmAR/yYVd3iHaxrFKBmCgP6RFpDc0j2q82p2YCBI6+xJcg5/zq6nmSKXaFSY7VqxcLxaYbJGmyMBxGXFibh3F8fyqnszTEY2FqEoSZRvTJYgUVmDM+JZVr55C6mu5U4Q+r72qRe7hZGDzBWDu8gakK83r4AzP0HFLDo7xUK8UgmqEhEEeA6F5+wcd/MzKyTKP8VwcfmKIBMyuy8L8XRwayFM0MPiwlNt3/9YUcXTKrz1YER28m80KCEvKWCQmQ49DxgdvkWcKgpAXaZyd2b7emgUfBe/D7MjTsI0PknHbRruv0duLO9RSaXApnYTME1EwaHddXPhkgKyFYUIJl5vpYpyp8y+8vGABX7R8ocWNpjkbkGIZbdbktHa0ujMDvNf/KUTNAR8/oOJJp9UIXzid7qwp+7s1wj46EDyHP7QfPPmZCikBV7Vs7O1fl0u8C0Yolbf+vwHfl5aT/6tPDRgR3Q=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
